name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    env:
      CURRENT_DATETIME: null
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: 実行
        run: |
          npm ci
          npx playwright install --with-deps
          npx update-browserslist-db@latest
          npx playwright test
        shell: bash
      - name: ビルド
        run: |
          npx prettier . -w
          npm run build
        shell: bash
      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo" # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: 生成したファイルをコミット
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # 念のため main に合わせる
          git checkout main

          # 変更を一時退避してから最新を取り込む
          git stash
          git fetch origin main
          git rebase origin/main
          git stash pop 2>/dev/null || true
          git add public/song_data/ranking.json
          git commit -m "song_name update at ${{ env.CURRENT_DATETIME }}" --allow-empty
          git push
        shell: bash
      - name: Pages アーティファクトをアップロード
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: GitHub Pages にデプロイ
        id: deployment
        uses: actions/deploy-pages@v5
